### ISSUE TITLE
add CD options for macos brew

### ISSUE THREAD

**Issue by georgettica** [riquito/tuc#95]
Hello!
I use mac and I found `tuc` to look very promising.
I would like to add CD support for it so each release (the first one will be forced) will upload a brew package with the changes.

I found https://github.com/extrawurst/gitui/blob/master/.github/workflows/cd.yml to look like a good way to go, but haven't tested it out.

is that a feature I should pursue or should cargo be the only way to install

**Comment by riquito** [comment]
Hi, thank you for the proposal, is interesting, but after giving it some thought I'd prefer to not adding that kind of workflow. I'm fine with preparing extra release artifacts for maintainers to use, but I don't want the pipeline to update any registry itself (a bit because it feels more safe to have an external entity - the maintainer - that vets whatever is released, and a bit because over time I'd have to know a fair share of details on various package managers).
